var NAVTREEINDEX1 =
{
"index.html#sec_layout":[0,8],
"index.html#sec_useage":[0,1],
"index.html#subsec_DetectorCons":[0,8,0],
"index.html#subsec_HSolenoidMagField":[0,8,1],
"index.html#subsec_Jlab":[0,7,1],
"index.html#subsec_Mainz":[0,7,0],
"index.html#subsec_PrimaryGeneratorAction":[0,8,2],
"index.html#subsec_bugs":[0,6,0],
"index.html#subsec_compiling":[0,3,0],
"index.html#subsec_hmolpolroot":[0,9,0],
"index.html#subsec_running":[0,3,1],
"index.html#subsec_todo":[0,6,1],
"index.html#subsubsec_Geometry":[0,8,0,0],
"index.html#subsubsec_Materials":[0,8,0,1],
"modules.html":[3],
"pages.html":[]
};
